version: "3"
services:
  db:
    image: postgres:14-alpine
    ports:
      - 127.0.0.1:5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db-data:/var/lib/postgres/data
  app:
    build: .
    ports:
      - 127.0.0.1:8000:8000
    command:
      - python3
      - -m
      - ftrack_webhooks

    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - FLASK_ENV=${FLASK_ENV}
      - DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}
      - WTF_CSRF_SECRET_KEY=${WTF_CSRF_SECRET_KEY}
      - SQLALCHEMY_ECHO=${SQLALCHEMY_ECHO}
      - SQLALCHEMY_TRACK_MODIFICATIONS=${SQLALCHEMY_TRACK_MODIFICATIONS}
    volumes:
      - .:/code

volumes:
  db-data:
